## Scan a docker image -> get a SARIF/SBOM report

name: SBOM/SCA Scout

on:
  workflow_dispatch:
    inputs:
      docker_image:
        description: 'The Docker image to scan'
        required: true
        default: 'python:3.9-slim'

jobs:
  scout:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Pull the GitHub input image or use the default
      - name: Pull the image
        run: docker pull ${{ github.event.inputs.docker_image }}

      - name: Docker Scout Scan - CVEs, Recommendations, Compare, SBOM
        uses: docker/scout-action@v1
        with:
          command: cves,recommendations,compare,sbom
          image: ${{ github.event.inputs.docker_image }}
          exit-code: false  # Prevent workflow from failing based on CVEs
          sarif-file: sca_scout.sarif
          output: sbom_scout.spdx.json
          format: spdx

      - name: Upload SBOM file as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom_scout.spdx.json
          path: sbom_scout.spdx.json

      - name: Upload SARIF file as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: sca_scout.sarif
          path: sca_scout.sarif

      # Optional: Only available on GitHub Enterprise or public repositories
      - name: Upload SARIF file to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: sca_scout.sarif
          category: Security/SCA

      - name: Submit SBOM to GitHub Dependency submission
        uses: advanced-security/spdx-dependency-submission-action@v0.1.1
